export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  RESIDENTS: "/residents",
  VISITORS: "/visitors",
  COMPLAINTS: "/complaints",
  MAINTENANCE: "/maintenance",
  PARKING: "/parking",
  PACKAGE_TRACKING: "/package-tracking",
  AMENITIES: "/amenities",
  NOTICE_BOARD: "/notice-board",
  SETTINGS: "/settings",
};
